import type {
  AccountDetails,
  AccountPreview,
  Bill,
  PortfolioSummary,
  BalanceSummary,
  CashFlowPoint,
  CategoryPageSummary,
  CategorySummary,
  DistributionSegment,
  Insight,
  MoneySummary,
  MonthGroup,
  SplitGroup,
  SplitMember,
  SplitPaySummary,
  TransactionSummary,
  UserGreeting,
} from '@/src/types/transaction'

/**
 * Placeholder API payloads. In production these arrive from typed service
 * hooks — components never own this data, they only receive it as props.
 */

export const greeting: UserGreeting = {
  name: 'Arjun',
  subtitle: 'Take control, split smart, save more.',
  unreadNotifications: 3,
}

export const balanceSummary: BalanceSummary = {
  totalBalance: 684000,
  monthlyChange: 8450,
  monthlyChangePercent: 12.4,
  accountCount: 4,
  currency: 'INR',
}

export const moneySummary: MoneySummary = {
  moneyIn: 320000,
  moneyOut: 235000,
  netBalance: 85000,
  bars: [40, 65, 30, 80, 55, 70, 45, 90, 60, 75],
  currency: 'INR',
}

export const accounts: AccountPreview[] = [
  {
    id: 'hdfc',
    name: 'Savings Account',
    institution: 'HDFC Bank',
    type: 'bank',
    balance: 82430,
    monthlyChangePercent: 8.2,
    currency: 'INR',
    accountsCount: 3,
    isPrimary: true,
    maskedNumber: '•••• 4821',
    lastSynced: '2 min ago',
  },
  {
    id: 'icici',
    name: 'Salary Account',
    institution: 'ICICI Bank',
    type: 'credit-card',
    balance: 48200,
    monthlyChangePercent: 5.6,
    currency: 'INR',
    accountsCount: 2,
    maskedNumber: '•••• 9034',
    lastSynced: '8 min ago',
  },
  {
    id: 'paytm',
    name: 'Wallet',
    institution: 'Paytm Wallet',
    type: 'wallet',
    balance: 5200,
    monthlyChangePercent: -3.1,
    currency: 'INR',
    accountsCount: 1,
    maskedNumber: '•••• 1177',
    lastSynced: '1 hr ago',
  },
  {
    id: 'axis',
    name: 'Debit Card',
    institution: 'Axis Bank',
    type: 'debit-card',
    balance: 25600,
    monthlyChangePercent: 2.4,
    currency: 'INR',
    accountsCount: 2,
    maskedNumber: '•••• 6650',
    lastSynced: '15 min ago',
  },
  {
    id: 'cash',
    name: 'In Hand',
    institution: 'Cash',
    type: 'cash',
    balance: 2150,
    monthlyChangePercent: 3.0,
    currency: 'INR',
    lastSynced: 'Manual',
  },
]

export const cashFlow: CashFlowPoint[] = [
  { label: '1 Jun', inflow: 22000, outflow: 8000 },
  { label: '5 Jun', inflow: 6000, outflow: 14000 },
  { label: '8 Jun', inflow: 48000, outflow: 11000 },
  { label: '12 Jun', inflow: 9000, outflow: 21000 },
  { label: '15 Jun', inflow: 30000, outflow: 16000 },
  { label: '19 Jun', inflow: 7000, outflow: 26000 },
  { label: '22 Jun', inflow: 52000, outflow: 12000 },
  { label: '26 Jun', inflow: 11000, outflow: 30000 },
  { label: '30 Jun', inflow: 35000, outflow: 18000 },
]

export const categories: CategorySummary[] = [
  {
    id: 'shopping',
    name: 'Shopping',
    icon: 'shopping-bag',
    amount: 48640,
    percent: 27.6,
    color: 'var(--negative)',
    budget: 50000,
    trend: 6.2,
    merchantCount: 14,
    group: 'wants',
  },
  {
    id: 'food',
    name: 'Food & Dining',
    icon: 'utensils',
    amount: 28350,
    percent: 16.1,
    color: 'var(--warning)',
    budget: 32000,
    trend: -4.1,
    merchantCount: 22,
    group: 'needs',
  },
  {
    id: 'bills',
    name: 'Bills & Utilities',
    icon: 'file-text',
    amount: 22180,
    percent: 12.6,
    color: 'var(--info)',
    budget: 24000,
    trend: 1.8,
    merchantCount: 6,
    group: 'needs',
  },
  {
    id: 'transport',
    name: 'Transport',
    icon: 'car',
    amount: 18420,
    percent: 10.5,
    color: 'var(--positive)',
    budget: 20000,
    trend: 3.4,
    merchantCount: 9,
    group: 'needs',
  },
  {
    id: 'entertainment',
    name: 'Entertainment',
    icon: 'play',
    amount: 12680,
    percent: 7.2,
    color: 'var(--primary)',
    budget: 15000,
    trend: -2.6,
    merchantCount: 7,
    group: 'wants',
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    icon: 'heart-pulse',
    amount: 9240,
    percent: 5.2,
    color: 'var(--negative)',
    budget: 12000,
    trend: 0.8,
    merchantCount: 4,
    group: 'lifestyle',
  },
  {
    id: 'education',
    name: 'Education',
    icon: 'book-open',
    amount: 8330,
    percent: 4.7,
    color: 'var(--info)',
    budget: 10000,
    trend: -1.2,
    merchantCount: 3,
    group: 'lifestyle',
  },
  {
    id: 'travel',
    name: 'Travel',
    icon: 'plane',
    amount: 6920,
    percent: 3.9,
    color: 'var(--info)',
    budget: 18000,
    trend: -8.4,
    merchantCount: 5,
    group: 'wants',
  },
  {
    id: 'others',
    name: 'Others',
    icon: 'more-horizontal',
    amount: 8260,
    percent: 4.7,
    color: 'var(--muted-foreground)',
    merchantCount: 11,
    group: 'others',
  },
]

export const splitPaySummary: SplitPaySummary = {
  youOwe: 4800,
  youAreOwed: 2300,
  netBalance: -2500,
  oweGroups: 3,
  owedGroups: 2,
  currency: 'INR',
}

export const insights: Insight[] = [
  {
    id: 'i1',
    icon: 'piggy-bank',
    title: 'Spending Insight',
    description: 'You spent ₹6,230 less on Food compared to last month.',
    cta: 'View details',
    tone: 'positive',
  },
]

export const transactionSummary: TransactionSummary = {
  income: 245000,
  expense: 152000,
  netFlow: 93000,
  incomeChangePercent: 12.5,
  expenseChangePercent: 8.3,
  incomeBars: [30, 50, 42, 65, 48, 70, 55, 80, 62, 88, 70, 92],
  expenseBars: [45, 30, 60, 38, 72, 44, 66, 50, 78, 55, 84, 60],
  currency: 'INR',
}

export const monthGroups: MonthGroup[] = [
  {
    id: 'jun-2026',
    month: 'June',
    year: 2026,
    totalSpent: 152000,
    currency: 'INR',
    transactions: [
      {
        id: 't1',
        merchant: 'Salary Credited',
        subtitle: 'Salary',
        category: 'Salary',
        icon: 'briefcase',
        account: 'HDFC Bank',
        type: 'income',
        amount: 50000,
        currency: 'INR',
        time: '09:21 AM',
        date: '22 Jun',
        status: 'completed',
        isRecurring: true,
      },
      {
        id: 't2',
        merchant: 'Lunch at Zomato',
        subtitle: 'Zomato',
        category: 'Food & Dining',
        icon: 'utensils',
        account: 'Paytm Wallet',
        type: 'expense',
        amount: 450,
        currency: 'INR',
        time: '01:14 PM',
        date: '22 Jun',
        status: 'completed',
        hasReceipt: true,
      },
      {
        id: 't3',
        merchant: 'Petrol',
        subtitle: 'IndianOil',
        category: 'Transport',
        icon: 'fuel',
        account: 'Axis Bank',
        type: 'expense',
        amount: 420,
        currency: 'INR',
        time: '06:45 PM',
        date: '22 Jun',
        status: 'completed',
      },
      {
        id: 't4',
        merchant: 'Cashback Received',
        subtitle: 'Paytm Wallet',
        category: 'Rewards',
        icon: 'wallet',
        account: 'Paytm Wallet',
        type: 'refund',
        amount: 210,
        currency: 'INR',
        time: '02:21 PM',
        date: '22 Jun',
        status: 'completed',
      },
      {
        id: 't5',
        merchant: 'Amazon Order',
        subtitle: 'Amazon',
        category: 'Shopping',
        icon: 'shopping-bag',
        account: 'ICICI Bank',
        type: 'expense',
        amount: 1280,
        currency: 'INR',
        time: '09:11 PM',
        date: '22 Jun',
        status: 'completed',
        hasReceipt: true,
        isSplit: true,
      },
      {
        id: 't6',
        merchant: 'Transfer to ICICI',
        subtitle: 'HDFC Bank → ICICI Bank',
        category: 'Transfer',
        icon: 'landmark',
        account: 'HDFC Bank',
        type: 'transfer',
        amount: 870,
        currency: 'INR',
        time: '11:02 AM',
        date: '22 Jun',
        status: 'completed',
      },
    ],
  },
  {
    id: 'may-2026',
    month: 'May',
    year: 2026,
    totalSpent: 140400,
    currency: 'INR',
    transactions: [
      {
        id: 't7',
        merchant: 'Netflix Subscription',
        subtitle: 'Netflix',
        category: 'Entertainment',
        icon: 'play',
        account: 'ICICI Bank',
        type: 'expense',
        amount: 649,
        currency: 'INR',
        time: '08:00 AM',
        date: '28 May',
        status: 'completed',
        isRecurring: true,
      },
      {
        id: 't8',
        merchant: 'Electricity Bill',
        subtitle: 'BESCOM',
        category: 'Bills & Utilities',
        icon: 'file-text',
        account: 'HDFC Bank',
        type: 'expense',
        amount: 2140,
        currency: 'INR',
        time: '10:32 AM',
        date: '25 May',
        status: 'completed',
        hasReceipt: true,
      },
      {
        id: 't9',
        merchant: 'Freelance Payment',
        subtitle: 'Upwork',
        category: 'Income',
        icon: 'briefcase',
        account: 'HDFC Bank',
        type: 'income',
        amount: 18500,
        currency: 'INR',
        time: '04:18 PM',
        date: '21 May',
        status: 'completed',
      },
    ],
  },
]

export const splitGroups: SplitGroup[] = [
  {
    id: 'goa',
    name: 'Goa Trip',
    emojiIcon: 'palmtree',
    coverColor: 'var(--negative)',
    membersSettled: 3,
    membersTotal: 5,
    memberAvatars: ['R', 'A', 'K', 'P'],
    extraMembers: 2,
    status: 'you-owe',
    amount: 1800,
    totalAmount: 10800,
    currency: 'INR',
  },
  {
    id: 'dinner',
    name: 'College Friends Dinner',
    emojiIcon: 'pizza',
    coverColor: 'var(--warning)',
    membersSettled: 2,
    membersTotal: 4,
    memberAvatars: ['R', 'S', 'M'],
    extraMembers: 1,
    status: 'you-are-owed',
    amount: 760,
    totalAmount: 2400,
    currency: 'INR',
  },
  {
    id: 'rent',
    name: 'Rent & Utilities',
    emojiIcon: 'home',
    coverColor: 'var(--primary)',
    membersSettled: 3,
    membersTotal: 3,
    memberAvatars: ['R', 'A', 'K'],
    extraMembers: 3,
    status: 'settled',
    amount: 0,
    totalAmount: 6000,
    currency: 'INR',
  },
  {
    id: 'movie',
    name: 'Weekend Outing',
    emojiIcon: 'popcorn',
    coverColor: 'var(--negative)',
    membersSettled: 1,
    membersTotal: 3,
    memberAvatars: ['P', 'K', 'S'],
    extraMembers: 1,
    status: 'you-owe',
    amount: 1240,
    totalAmount: 3500,
    currency: 'INR',
  },
]

export const splitMembers: SplitMember[] = [
  { id: 'm1', name: 'Rohit Sharma', avatar: 'RS', netBalance: 1600, direction: 'you-owe' },
  { id: 'm2', name: 'Ananya Gupta', avatar: 'AG', netBalance: 1250, direction: 'owes-you' },
  { id: 'm3', name: 'Karan Mehta', avatar: 'KM', netBalance: 1000, direction: 'you-owe' },
  { id: 'm4', name: 'Priya Singh', avatar: 'PS', netBalance: 1050, direction: 'owes-you' },
]

/** Dynamic details keyed by account id — shape varies per account type. */
export const accountDetailsById: Record<string, AccountDetails> = {
  hdfc: {
    accountId: 'hdfc',
    currency: 'INR',
    primaryAmountLabel: 'Available Balance',
    primaryAmount: 82430,
    secondaryAmountLabel: 'Ledger Balance',
    secondaryAmount: 84210,
    progressPercent: 62,
    footnoteLabel: 'Monthly Change',
    footnoteValue: '+₹8,450 (8.2%)',
    fields: [
      { id: 'type', label: 'Account Type', value: 'Savings Account', icon: 'landmark' },
      { id: 'number', label: 'Account Number', value: '•••• 4821', icon: 'hash', copyable: true },
      { id: 'ifsc', label: 'IFSC Code', value: 'HDFC0001234', icon: 'qr-code', copyable: true },
      { id: 'branch', label: 'Branch', value: 'Connaught Place, New Delhi', icon: 'map-pin' },
      { id: 'opened', label: 'Opened On', value: '12 Jan 2023', icon: 'calendar' },
      { id: 'interest', label: 'Interest Rate', value: '2.75% p.a.', icon: 'percent' },
      { id: 'synced', label: 'Last Synced', value: 'Today, 08:45 AM', icon: 'clock' },
      { id: 'status', label: 'Status', value: 'Active', icon: 'check-circle', tone: 'positive' },
    ],
  },
  icici: {
    accountId: 'icici',
    currency: 'INR',
    primaryAmountLabel: 'Outstanding',
    primaryAmount: 48200,
    secondaryAmountLabel: 'Available Limit',
    secondaryAmount: 151800,
    progressPercent: 24,
    footnoteLabel: 'Credit Utilization',
    footnoteValue: '24% of ₹2,00,000',
    fields: [
      { id: 'type', label: 'Card Type', value: 'Credit Card', icon: 'credit-card' },
      { id: 'number', label: 'Card Number', value: '•••• 9034', icon: 'hash', copyable: true },
      { id: 'statement', label: 'Statement Date', value: '01 Jul 2026', icon: 'calendar' },
      { id: 'due', label: 'Due Date', value: '18 Jul 2026', icon: 'calendar-clock' },
      { id: 'min-due', label: 'Minimum Due', value: '₹2,410', icon: 'banknote' },
      { id: 'rewards', label: 'Reward Points', value: '12,480 pts', icon: 'sparkles', tone: 'positive' },
      { id: 'issuer', label: 'Issuer', value: 'ICICI Bank', icon: 'landmark' },
      { id: 'status', label: 'Status', value: 'Active', icon: 'check-circle', tone: 'positive' },
    ],
  },
  paytm: {
    accountId: 'paytm',
    currency: 'INR',
    primaryAmountLabel: 'Current Balance',
    primaryAmount: 5200,
    secondaryAmountLabel: 'Monthly Usage',
    secondaryAmount: 8340,
    progressPercent: 42,
    footnoteLabel: 'Daily Limit',
    footnoteValue: '₹10,000 / day',
    fields: [
      { id: 'type', label: 'Wallet Type', value: 'Prepaid Wallet', icon: 'wallet' },
      { id: 'linked', label: 'Linked Number', value: '•••• 98210', icon: 'smartphone', copyable: true },
      { id: 'upi', label: 'UPI ID', value: 'arjun@paytm', icon: 'at-sign', copyable: true },
      { id: 'bank', label: 'Linked Bank', value: 'HDFC Bank', icon: 'landmark' },
      { id: 'kyc', label: 'KYC', value: 'Full KYC', icon: 'shield-check', tone: 'positive' },
      { id: 'synced', label: 'Last Synced', value: 'Today, 07:58 AM', icon: 'clock' },
      { id: 'status', label: 'Status', value: 'Active', icon: 'check-circle', tone: 'positive' },
    ],
  },
  axis: {
    accountId: 'axis',
    currency: 'INR',
    primaryAmountLabel: 'Available',
    primaryAmount: 25600,
    secondaryAmountLabel: 'ATM Limit',
    secondaryAmount: 50000,
    progressPercent: 51,
    footnoteLabel: 'Online Limit',
    footnoteValue: '₹1,00,000 / day',
    fields: [
      { id: 'type', label: 'Card Type', value: 'Debit Card', icon: 'credit-card' },
      { id: 'number', label: 'Card Number', value: '•••• 6650', icon: 'hash', copyable: true },
      { id: 'bank', label: 'Linked Bank', value: 'Axis Bank', icon: 'landmark' },
      { id: 'intl', label: 'International Usage', value: 'Enabled', icon: 'globe', tone: 'positive' },
      { id: 'contactless', label: 'Contactless', value: 'Enabled', icon: 'wifi', tone: 'positive' },
      { id: 'synced', label: 'Last Synced', value: 'Today, 08:30 AM', icon: 'clock' },
      { id: 'status', label: 'Status', value: 'Active', icon: 'check-circle', tone: 'positive' },
    ],
  },
  cash: {
    accountId: 'cash',
    currency: 'INR',
    primaryAmountLabel: 'Total Cash',
    primaryAmount: 2150,
    secondaryAmountLabel: 'Emergency Cash',
    secondaryAmount: 1000,
    progressPercent: 47,
    footnoteLabel: 'Last Updated',
    footnoteValue: 'Today, 09:20 AM',
    fields: [
      { id: 'home', label: 'Home Cash', value: '₹1,200', icon: 'home' },
      { id: 'office', label: 'Office Cash', value: '₹450', icon: 'briefcase' },
      { id: 'travel', label: 'Travel Cash', value: '₹500', icon: 'plane' },
      { id: 'location', label: 'Location', value: 'Home Safe', icon: 'map-pin' },
      { id: 'denomination', label: 'Denomination', value: 'Mixed', icon: 'banknote' },
      { id: 'edited', label: 'Last Edited By', value: 'You', icon: 'user' },
      { id: 'security', label: 'Security', value: 'Encrypted', icon: 'shield-check', tone: 'positive' },
    ],
  },
}

export const portfolioSummary: PortfolioSummary = {
  totalValue: 245670.8,
  todaysChange: 2850.45,
  todaysChangePercent: 1.17,
  holdings: 12,
  totalGain: 18670.3,
  totalGainPercent: 8.21,
  sparkline: [30, 42, 38, 55, 48, 62, 58, 74, 66, 82, 78, 92],
  currency: 'INR',
}

export const upcomingBills: Bill[] = [
  {
    id: 'airtel',
    name: 'Airtel Mobile',
    provider: 'AutoPay',
    icon: 'smartphone',
    color: 'var(--negative)',
    amount: 549,
    dueLabel: '28 May 2026',
    autopay: true,
    currency: 'INR',
  },
  {
    id: 'netflix',
    name: 'Netflix Subscription',
    provider: 'AutoPay',
    icon: 'play',
    color: 'var(--negative)',
    amount: 649,
    dueLabel: '30 May 2026',
    autopay: true,
    currency: 'INR',
  },
  {
    id: 'electricity',
    name: 'Electricity Bill',
    provider: 'BESCOM',
    icon: 'zap',
    color: 'var(--warning)',
    amount: 1230,
    dueLabel: '02 Jun 2026',
    autopay: false,
    currency: 'INR',
  },
  {
    id: 'sip',
    name: 'Mutual Fund SIP',
    provider: 'AutoPay',
    icon: 'trending-up',
    color: 'var(--info)',
    amount: 5000,
    dueLabel: '05 Jun 2026',
    autopay: true,
    currency: 'INR',
  },
]

export const accountInsights: Insight[] = [
  {
    id: 'ai1',
    icon: 'sparkles',
    title: 'Savings up',
    description: 'You have ₹18,450 more in savings this month compared to last month. Keep going!',
    tone: 'positive',
  },
  {
    id: 'ai2',
    icon: 'credit-card',
    title: 'Credit utilization',
    description: 'Your ICICI credit utilization is at 24% — well within the healthy 30% range.',
    tone: 'info',
  },
  {
    id: 'ai3',
    icon: 'wallet',
    title: 'Wallet inactive',
    description: 'Your Paytm Wallet has had no activity for 6 days. ₹5,200 is sitting idle.',
    tone: 'warning',
  },
]

export const accountDistribution: DistributionSegment[] = [
  { id: 'banks', label: 'Bank Accounts', amount: 132430, percent: 46, color: 'var(--primary)' },
  { id: 'credit', label: 'Credit Cards', amount: 48200, percent: 17, color: 'var(--info)' },
  { id: 'debit', label: 'Debit Cards', amount: 25600, percent: 9, color: 'var(--warning)' },
  { id: 'wallets', label: 'Wallets & Cash', amount: 77770, percent: 28, color: 'var(--positive)' },
]

/** Categories page headline metrics — single source of truth for the page. */
export const categoryPageSummary: CategoryPageSummary = {
  totalSpent: 176020,
  changePercent: 12.4,
  month: 'June 2026',
  savedAmount: 6230,
  comparedCategory: 'Food',
  currency: 'INR',
}
