"use client";

import Link from "next/link";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Eye, EyeOff, Landmark, Plus, ReceiptText, Sparkles, UsersRound } from "lucide-react";
import { useState, type ReactNode } from "react";
import { GlassCard } from "@/src/design-system";
import { cn } from "@/src/lib/utils";
import type { AuroraOverviewModel } from "./contracts";

const money = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);

function Section({ title, action, children }: { title: string; action?: { href: string; label: string }; children: ReactNode }) {
  return <section className="space-y-3"><div className="flex items-center justify-between gap-4"><h2 className="text-base font-semibold text-[var(--text-primary)]">{title}</h2>{action && <Link href={action.href} className="text-sm font-medium text-[var(--aurora-cyan)] hover:text-[var(--aurora-blue)]">{action.label}</Link>}</div>{children}</section>;
}

function Money({ value, hidden = false, className }: { value: number; hidden?: boolean; className?: string }) {
  const reduceMotion = useReducedMotion();
  return <motion.span initial={reduceMotion ? false : { opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.45 }} className={cn("tabular-nums", hidden && "select-none blur-md", className)}>{hidden ? "••••••" : money(value)}</motion.span>;
}

export function AuroraOverview({ data, onAddTransaction }: { data: AuroraOverviewModel; onAddTransaction: () => void }) {
  const [hidden, setHidden] = useState(false);
  const name = data.greetingName || "there";
  const positive = data.monthlyChange >= 0;
  const highestCategory = data.categories[0];

  return <div className="aurora-canvas min-h-dvh"><div className="mx-auto w-full max-w-7xl space-y-7 px-4 pb-28 pt-5 sm:px-6 lg:space-y-8 lg:px-8 lg:pb-10 lg:pt-8">
    <header className="flex items-start justify-between gap-4"><div><p className="text-sm text-[var(--text-secondary)]">Your financial overview</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-[var(--text-primary)] sm:text-3xl">Good to see you, {name}</h1></div><div className="grid h-10 w-10 place-items-center rounded-2xl aurora-glass text-[var(--aurora-cyan)]"><Sparkles size={18} /></div></header>

    <GlassCard tone="soft" glow="violet" padding="lg" className="overflow-hidden"><div className="absolute -right-16 -top-20 h-52 w-52 rounded-full bg-[var(--aurora-cyan)]/20 blur-3xl" /><div className="absolute -bottom-24 left-1/3 h-48 w-48 rounded-full bg-[var(--aurora-violet)]/40 blur-3xl" /><div className="relative"><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-[var(--text-secondary)]">Total balance</p><p className="mt-2 text-3xl font-bold tracking-tight text-[var(--text-primary)] sm:text-4xl"><Money value={data.balance} hidden={hidden} /></p><p className="mt-1 text-sm text-[var(--text-secondary)]">Across {data.accountCount} accounts</p></div><button onClick={() => setHidden((value) => !value)} className="grid h-9 w-9 place-items-center rounded-xl bg-white/10 text-[var(--text-primary)] transition hover:bg-white/20" aria-label={hidden ? "Show balance" : "Hide balance"}>{hidden ? <Eye size={18} /> : <EyeOff size={18} />}</button></div><div className="mt-7 grid grid-cols-2 gap-3 border-t border-[var(--aurora-glass-border)] pt-4"><div><p className="text-xs text-[var(--text-secondary)]">Net worth</p><p className="mt-1 font-semibold text-[var(--text-primary)]"><Money value={data.netWorth} hidden={hidden} /></p></div><div><p className="text-xs text-[var(--text-secondary)]">Monthly change</p><p className={cn("mt-1 flex items-center gap-1 font-semibold", positive ? "text-emerald-400" : "text-rose-400")}>{positive ? <ArrowUpRight size={16} /> : <ArrowDownRight size={16} />}{Math.abs(data.monthlyChange).toFixed(1)}%</p></div></div></div></GlassCard>

    <div className="grid grid-cols-3 gap-3"><Action icon={<Plus size={19} />} label="Add expense" onClick={onAddTransaction} /><Action icon={<ReceiptText size={19} />} label="Transactions" href="/transactions" /><Action icon={<UsersRound size={19} />} label="Split a bill" href="/split" /></div>

    <Section title="Cash flow"><div className="grid gap-3 sm:grid-cols-2"><FlowCard label="Money in" value={data.income} accent="text-emerald-400" /><FlowCard label="Money out" value={data.expenses} accent="text-rose-400" /></div></Section>

    <div className="grid gap-6 lg:grid-cols-2"><Section title="Spending by category" action={{ href: "/categories", label: "View all" }}><GlassCard padding="md" className="space-y-4">{data.categories.length ? data.categories.map((category, index) => <div key={category.name}><div className="mb-2 flex justify-between text-sm"><span className="font-medium text-[var(--text-primary)]">{category.name}</span><span className="text-[var(--text-secondary)]">{money(category.amount)}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/10"><motion.div className="h-full rounded-full bg-[var(--aurora-gradient)]" initial={{ width: 0 }} animate={{ width: `${category.percentage}%` }} transition={{ delay: index * 0.06, duration: 0.5 }} /></div></div>) : <p className="py-6 text-center text-sm text-[var(--text-secondary)]">No spending yet this period.</p>}</GlassCard></Section>
      <Section title="Your accounts" action={{ href: "/accounts", label: "Manage" }}><GlassCard padding="none" className="overflow-hidden">{data.accounts.slice(0, 3).map((account) => <Link href="/accounts" key={account.id} className="flex items-center gap-3 border-b border-[var(--aurora-glass-border)] px-4 py-3 last:border-b-0 hover:bg-white/5"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[var(--aurora-gradient-soft)] text-[var(--aurora-cyan)]"><Landmark size={17} /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-[var(--text-primary)]">{account.name}</p><p className="text-xs text-[var(--text-secondary)]">{account.kind}</p></div><p className="text-sm font-semibold text-[var(--text-primary)]">{money(account.balance)}</p></Link>)}</GlassCard></Section></div>

    <div className="grid gap-6 lg:grid-cols-2"><Section title="SplitPay" action={{ href: "/split", label: "Open SplitPay" }}><GlassCard interactive padding="md" className="flex items-center gap-4"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[var(--aurora-gradient-soft)] text-[var(--aurora-cyan)]"><UsersRound size={21} /></div><div className="flex-1"><p className="font-medium text-[var(--text-primary)]">{data.splitPay.groupCount ? `${data.splitPay.groupCount} active groups` : "Split expenses with friends"}</p><p className="mt-0.5 text-sm text-[var(--text-secondary)]">{data.splitPay.outstanding ? `${money(data.splitPay.outstanding)} to settle` : "Create a group to get started"}</p></div></GlassCard></Section><Section title="Insight"><GlassCard tone="strong" padding="md" className="flex gap-3"><Sparkles className="mt-0.5 shrink-0 text-[var(--aurora-amber)]" size={19} /><p className="text-sm leading-6 text-[var(--text-secondary)]">{highestCategory ? `${highestCategory.name} is your largest spending category this period.` : "Add transactions to unlock personal spending insights."}</p></GlassCard></Section></div>

    <Section title="Recent activity" action={{ href: "/transactions", label: "See all" }}><GlassCard padding="none" className="overflow-hidden">{data.activities.length ? data.activities.map((activity) => <Link href="/transactions" key={activity.id} className="flex items-center gap-3 border-b border-[var(--aurora-glass-border)] px-4 py-3.5 last:border-b-0 hover:bg-white/5"><div className={cn("grid h-9 w-9 place-items-center rounded-xl", activity.direction === "debit" ? "bg-rose-400/10 text-rose-400" : "bg-emerald-400/10 text-emerald-400")}>{activity.direction === "debit" ? <ArrowDownRight size={17} /> : <ArrowUpRight size={17} />}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-[var(--text-primary)]">{activity.title}</p><p className="truncate text-xs text-[var(--text-secondary)]">{activity.subtitle}</p></div><p className={cn("text-sm font-semibold", activity.direction === "debit" ? "text-[var(--text-primary)]" : "text-emerald-400")}>{activity.direction === "debit" ? "−" : "+"}{money(activity.amount)}</p></Link>) : <p className="p-8 text-center text-sm text-[var(--text-secondary)]">No recent activity.</p>}</GlassCard></Section>
  </div></div>;
}

function Action({ icon, label, href, onClick }: { icon: ReactNode; label: string; href?: string; onClick?: () => void }) { const content = <><span className="grid h-9 w-9 place-items-center rounded-xl bg-white/10 text-[var(--aurora-cyan)]">{icon}</span><span>{label}</span></>; const className = "flex min-h-20 flex-col items-center justify-center gap-1 rounded-[var(--aurora-radius-card)] aurora-glass px-2 text-center text-xs font-medium text-[var(--text-primary)] transition hover:-translate-y-0.5 hover:bg-white/10"; return href ? <Link href={href} className={className}>{content}</Link> : <button type="button" onClick={onClick} className={className}>{content}</button>; }
function FlowCard({ label, value, accent }: { label: string; value: number; accent: string }) { return <GlassCard interactive padding="md"><p className="text-sm text-[var(--text-secondary)]">{label}</p><p className={cn("mt-2 text-xl font-semibold", accent)}>{money(value)}</p></GlassCard>; }
