"use client";

import { ArrowDownRight, ArrowUpRight, ArrowUpDown, ChevronRight, FileText, Plus, Search, X } from "lucide-react";
import { useMemo, useState } from "react";
import { GlassCard } from "@/src/shared/components/glass-card";
import { cn } from "@/src/lib/utils";
import type { AuroraTransaction, AuroraTransactionFeed } from "./contracts";

const amount = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Math.abs(value));
type Filter = "all" | "income" | "expense";

export function AuroraTransactions({ feed, onNewTransaction }: { feed: AuroraTransactionFeed; onNewTransaction: () => void }) {
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState<Filter>("all");
  const [ascending, setAscending] = useState(false);
  const [selected, setSelected] = useState<AuroraTransaction | null>(null);
  const visible = useMemo(() => feed.transactions.filter((item) => {
    const matches = `${item.payee} ${item.category ?? ""} ${item.account}`.toLowerCase().includes(query.toLowerCase());
    const type = filter === "all" || filter === "income" && item.amount > 0 || filter === "expense" && item.amount < 0;
    return matches && type;
  }).sort((a, b) => ascending ? a.occurredAt.getTime() - b.occurredAt.getTime() : b.occurredAt.getTime() - a.occurredAt.getTime()), [feed.transactions, query, filter, ascending]);
  const groups = useMemo(() => groupMonths(visible), [visible]);
  const counts = { all: feed.transactions.length, income: feed.transactions.filter((item) => item.amount > 0).length, expense: feed.transactions.filter((item) => item.amount < 0).length };

  return <div className="aurora-canvas min-h-dvh"><div className="mx-auto w-full max-w-5xl px-4 pb-28 pt-5 sm:px-6 lg:pb-10 lg:pt-8">
    <header className="mb-5 flex items-start justify-between gap-4"><div><p className="text-sm text-[var(--text-secondary)]">Your money, in motion</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-[var(--text-primary)] sm:text-3xl">Transactions</h1></div><AuroraButton size="sm" icon={<Plus size={16} />} onClick={onNewTransaction}>Add</AuroraButton></header>
    <div className="mb-5 grid grid-cols-3 gap-2 sm:gap-3"><Summary label="In" value={feed.income} tone="income" /><Summary label="Out" value={feed.expenses} tone="expense" /><Summary label="Flow" value={feed.net} tone={feed.net >= 0 ? "income" : "expense"} /></div>
    <div className="sticky top-16 z-20 -mx-4 mb-5 border-y border-[var(--aurora-glass-border)] bg-[var(--surface-bg)]/85 px-4 py-3 backdrop-blur-xl sm:mx-0 sm:rounded-2xl sm:border sm:px-3"><div className="flex items-center gap-2"><div className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[var(--text-muted)]" size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search transactions" className="h-10 w-full rounded-xl border border-[var(--aurora-glass-border)] bg-white/5 pl-9 pr-8 text-sm text-[var(--text-primary)] outline-none placeholder:text-[var(--text-muted)] focus:border-[var(--aurora-cyan)]" />{query && <button type="button" aria-label="Clear search" onClick={() => setQuery("")} className="absolute right-2 top-1/2 -translate-y-1/2 text-[var(--text-muted)]"><X size={15} /></button>}</div><button type="button" aria-label="Reverse sort" onClick={() => setAscending((state) => !state)} className="grid h-10 w-10 place-items-center rounded-xl aurora-glass text-[var(--text-secondary)]"><ArrowUpDown size={17} /></button></div><div className="mt-3 flex gap-2 overflow-x-auto pb-0.5">{(["all", "income", "expense"] as Filter[]).map((item) => <button type="button" key={item} onClick={() => setFilter(item)} className={cn("shrink-0 rounded-full border px-3 py-1.5 text-xs font-semibold capitalize transition", filter === item ? "border-transparent bg-[var(--aurora-gradient)] text-white shadow-[var(--aurora-glow-violet)]" : "border-[var(--aurora-glass-border)] bg-white/5 text-[var(--text-secondary)]")}>{item} <span className="ml-1 opacity-75">{counts[item]}</span></button>)}</div></div>
    {groups.length ? <div className="space-y-7">{groups.map(([month, items]) => <section key={month}><div className="mb-3 flex items-center gap-3"><h2 className="text-sm font-semibold text-[var(--text-primary)]">{month}</h2><div className="h-px flex-1 bg-[var(--aurora-glass-border)]" /><span className="text-xs text-[var(--text-secondary)]">{amount(items.reduce((total, item) => total + item.amount, 0))}</span></div><div className="relative pl-6 before:absolute before:bottom-3 before:left-[7px] before:top-3 before:w-px before:bg-gradient-to-b before:from-[var(--aurora-cyan)] before:via-[var(--aurora-violet)] before:to-transparent">{items.map((item, index) => <TimelineItem key={item.id} item={item} index={index} onSelect={() => setSelected(item)} />)}</div></section>)}</div> : <GlassCard className="py-14 text-center"><FileText className="mx-auto mb-3 text-[var(--aurora-cyan)]" size={25} /><p className="font-medium text-[var(--text-primary)]">No matching transactions</p><p className="mt-1 text-sm text-[var(--text-secondary)]">Try another search or filter.</p></GlassCard>}
  </div><TransactionSheet transaction={selected} onDismiss={() => setSelected(null)} /></div>;
}

function Summary({ label, value, tone }: { label: string; value: number; tone: "income" | "expense" }) { return <GlassCard padding="sm" className="min-w-0"><p className="text-[11px] text-[var(--text-secondary)]">{label}</p><p className={cn("mt-1 truncate text-sm font-bold tabular-nums sm:text-base", tone === "income" ? "text-emerald-400" : "text-rose-400")}>{value < 0 ? "−" : ""}{amount(value)}</p></GlassCard>; }
function TimelineItem({ item, index, onSelect }: { item: AuroraTransaction; index: number; onSelect: () => void }) { const positive = item.amount > 0; return <button type="button" onClick={onSelect} className="relative mb-3 block w-full text-left last:mb-0"><span className={cn("absolute -left-6 top-5 h-3.5 w-3.5 rounded-full border-2 border-[var(--surface-bg)] shadow-[0_0_12px_currentColor]", positive ? "bg-emerald-400 text-emerald-400" : "bg-[var(--aurora-pink)] text-[var(--aurora-pink)]")} /><GlassCard interactive padding="sm" className="flex items-center gap-3"><span className={cn("grid h-10 w-10 place-items-center rounded-xl", positive ? "bg-emerald-400/10 text-emerald-400" : "bg-rose-400/10 text-rose-400")}>{positive ? <ArrowDownRight size={18} /> : <ArrowUpRight size={18} />}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-[var(--text-primary)]">{item.payee}</span><span className="mt-0.5 block truncate text-xs text-[var(--text-secondary)]">{item.category ?? "Uncategorized"} · {item.account}</span></span><span className="text-right"><span className={cn("block text-sm font-bold tabular-nums", positive ? "text-emerald-400" : "text-[var(--text-primary)]")}>{positive ? "+" : "−"}{amount(item.amount)}</span><span className="text-[10px] text-[var(--text-muted)]">{item.occurredAt.toLocaleDateString("en-IN", { day: "numeric", month: "short" })}</span></span><ChevronRight className="text-[var(--text-muted)]" size={15} /></GlassCard></button>; }
function TransactionSheet({ transaction, onDismiss }: { transaction: AuroraTransaction | null; onDismiss: () => void }) { return <AuroraSheet open={!!transaction} onDismiss={onDismiss}><div className="space-y-5">{transaction && <><div className="text-center"><p className="text-sm text-[var(--text-secondary)]">{transaction.amount > 0 ? "Money received" : "Money spent"}</p><p className={cn("mt-1 text-3xl font-bold", transaction.amount > 0 ? "text-emerald-400" : "text-[var(--text-primary)]")}>{transaction.amount > 0 ? "+" : "−"}{amount(transaction.amount)}</p></div><div className="rounded-2xl aurora-glass p-4 text-sm"><Detail label="Payee" value={transaction.payee} /><Detail label="Category" value={transaction.category ?? "Uncategorized"} /><Detail label="Account" value={transaction.account} /><Detail label="Date" value={transaction.occurredAt.toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })} />{transaction.notes && <Detail label="Notes" value={transaction.notes} />}</div></>}</div></AuroraSheet>; }
function Detail({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4 border-b border-[var(--aurora-glass-border)] py-3 last:border-b-0"><span className="text-[var(--text-secondary)]">{label}</span><span className="text-right font-medium text-[var(--text-primary)]">{value}</span></div>; }
function groupMonths(items: AuroraTransaction[]) { const groups = new Map<string, AuroraTransaction[]>(); for (const item of items) { const key = item.occurredAt.toLocaleDateString("en-IN", { month: "long", year: "numeric" }); groups.set(key, [...(groups.get(key) ?? []), item]); } return Array.from(groups.entries()); }
